---
application:
  name: "dockerized-spring-boot-app"
  project: "dockerized-spring-boot-app"
  organization: "QoveryCommunity"
routers:
- name: "main-dockerized-spring-boot-app"
  routes:
  - application_name: "dockerized-spring-boot-app"
    paths:
    - "/*"
